name: Sync with Veracode GitHub Actions Integrations Repository

on:
  schedule:
    - cron: 0 14 * * *
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: | 
            console.log(JSON.stringify(context.repo.owner))
            console.log(JSON.stringify(context.repo.repo))
      # - name: Set a Delay
      #   run: sleep $(( RANDOM % 10 ))
      # - name: Dispatch Sync Event
      #   uses: actions/github-script@v7
      #   with:
      #     github-token: ${{ secrets.MY_PAT }}
      #     script: |
      #       await github.rest.repos.createDispatchEvent({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         event_type: 'sync-veracode-repo',
      #       });
